language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer install --prefer-source
  - export LANG=C
  - export PATH=vendor/bin:$PATH

script:
  - behat -fprogress --strict
